export const ADD_EXPENSE = "ADD_EXPENSE";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY= "REMOVE_CATEGORY";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE"
export const LOGGED_IN_USER = "LOGGED_IN_USER"
export const CLEAR_STORE = "CLEAR_STORE"